name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12-alpine
    steps:
      - name: Packages
        run: apk add --no-cache ca-certificates git openssh-client tar
      - name: Branch name
        run: echo "v5-${{ runner.os }}-${GITHUB_REF##*/}"

      - name: Set branch name
        id: set_branch
        run: echo ::set-output name=branch::${GITHUB_REF##*/}
      - name: Check output
        run: echo ${{ steps.set_branch.outputs.branch }}
      - name: Cache - Eslint
        uses: actions/cache@v2
        with:
          path: tmp/.eslintcache
          key: v5-eslint-${{ runner.os }}-${{ steps.set_branch.outputs.branch }}
          restore-keys: |
            v5-eslint-${{ runner.os }}-${{ steps.set_branch.outputs.branch }}
            v5-eslint-${{ runner.os }}-
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Cache - Eslint using env.BRANCH
        uses: actions/cache@v2
        with:
          path: tmp/.eslintcache
          key: v5-eslint-${{ runner.os }}-${{ env.BRANCH }}
          restore-keys: |
            v5-eslint-${{ runner.os }}-${{ env.BRANCHs }}
            v5-eslint-${{ runner.os }}-
      - uses: actions/checkout@v2
      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: '@seismic/mantle'
          # default types: https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-changelog-conventionalcommits/writer-opts.js#L171-L184
          # hidden sections are shown if breaking change
          changelog-types: '[{"type":"feat","section":":rocket:&nbsp;&nbsp;Features"},{"type":"fix","section":":bug:&nbsp;&nbsp;Bug Fixes"},{"type":"refactor","section":":sunglasses:&nbsp;&nbsp;Refactor","hidden":true},{"type":"perf","section":":bullettrain_front:&nbsp;&nbsp;Performance Improvements"}]'
      - name: Release info
        if: ${{ steps.release.outputs }}
        run: echo "${{ toJSON(steps.release.outputs) }}"
        continue-on-error: true
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' && steps.release.outputs.release_created }}
        run: echo "Publishing"
      - name: Docs
        if: ${{ contains(github.event.head_commit.message, '[update styleguide]') || (github.ref == 'refs/heads/master' && steps.release.outputs.release_created) }}
        run: echo "Documentation"
